version: '2'

services:

  orderer.orderermanagement.com:
    container_name: orderer.orderermanagement.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/orderermanagement.com/orderers/orderer.orderermanagement.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/orderermanagement.com/orderers/orderer.orderermanagement.com/tls/:/var/hyperledger/orderer/tls
        - orderer.orderermanagement.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.buyer.orderermanagement.com:
    container_name: peer0.buyer.orderermanagement.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.buyer.orderermanagement.com
      - CORE_PEER_ADDRESS=peer0.buyer.orderermanagement.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.buyer.orderermanagement.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.buyer.orderermanagement.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.buyer.orderermanagement.com:7051
      - CORE_PEER_LOCALMSPID=BuyerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/buyer.orderermanagement.com/peers/peer0.buyer.orderermanagement.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/buyer.orderermanagement.com/peers/peer0.buyer.orderermanagement.com/tls:/etc/hyperledger/fabric/tls
        - peer0.buyer.orderermanagement.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.buyer.orderermanagement.com:
    container_name: peer1.buyer.orderermanagement.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.buyer.orderermanagement.com
      - CORE_PEER_ADDRESS=peer1.buyer.orderermanagement.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.buyer.orderermanagement.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.buyer.orderermanagement.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.buyer.orderermanagement.com:7051
      - CORE_PEER_LOCALMSPID=BuyerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/buyer.orderermanagement.com/peers/peer1.buyer.orderermanagement.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/buyer.orderermanagement.com/peers/peer1.buyer.orderermanagement.com/tls:/etc/hyperledger/fabric/tls
        - peer1.buyer.orderermanagement.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer0.seller.orderermanagement.com:
    container_name: peer0.seller.orderermanagement.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.seller.orderermanagement.com
      - CORE_PEER_ADDRESS=peer0.seller.orderermanagement.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.seller.orderermanagement.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.seller.orderermanagement.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.seller.orderermanagement.com:12051
      - CORE_PEER_LOCALMSPID=SellerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/seller.orderermanagement.com/peers/peer0.seller.orderermanagement.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/seller.orderermanagement.com/peers/peer0.seller.orderermanagement.com/tls:/etc/hyperledger/fabric/tls
        - peer0.seller.orderermanagement.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.seller.orderermanagement.com:
    container_name: peer1.seller.orderermanagement.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.seller.orderermanagement.com
      - CORE_PEER_ADDRESS=peer1.seller.orderermanagement.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.seller.orderermanagement.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.seller.orderermanagement.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.seller.orderermanagement.com:11051
      - CORE_PEER_LOCALMSPID=SellerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/seller.orderermanagement.com/peers/peer1.seller.orderermanagement.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/seller.orderermanagement.com/peers/peer1.seller.orderermanagement.com/tls:/etc/hyperledger/fabric/tls
        - peer1.seller.orderermanagement.com:/var/hyperledger/production
    ports:
      - 12051:12051